### ISSUE TITLE
Uses old SOAP API instead of new JSON API as defined by BID PG v3.0

### ISSUE THREAD

**Issue by Xestero** [richarddd/node-bank-id#2]
Great library, but as of BankID Relying Party Guidelines v3.0 (released 2018-02-16) the service (V5) replaces XML/SOAP with JSON, it also includes a cancel method.

**Comment by richarddd** [comment]
@Xestero oh thanks for the info. Will update ASAP!

**Comment by richarddd** [comment]
Fixed in version 2.0
